// packages/solidjs/src/components/render-block.tsx
import { type SuperJSONObject } from "@backflipjs/client";
import { For } from "solid-js";

import { useContext } from "../hooks/use-context";

interface RenderBlockProps {
  component: string;
  props?: SuperJSONObject;
  children?: RenderBlockProps[];
}

export function RenderBlock({
  component,
  props = {},
  children = [],
}: RenderBlockProps) {
  const context = useContext();
  const registry = context?.().registry;
  const El = registry?.get(component);

  if (!El) {
    return null;
  }

  return (
    <El {...props}>
      <For each={children}>
        {(child: RenderBlockProps) => <RenderBlock {...child} />}
      </For>
    </El>
  );
}

// packages/svelte/src/lib/components/render-block.svelte
<script lang="ts">
  import { type RenderedComponentConfig } from "@backflipjs/client";

  import { getRegistry } from "../utils/registry.js";

  const registry = getRegistry();

  export let config: RenderedComponentConfig;
  let component = registry.get(config.component);
</script>

{#if component}
  <svelte:component this={component} {...config.props}>
    {#if config.children}
      {#each config.children as child}
        <svelte:self config={child} />
      {/each}
    {/if}
  </svelte:component>
{/if}
