// packages/svelte/src/lib/components/render-component.svelte
<script lang="ts">
  import {
    type SuperJSONObject,
    type RenderedComponentConfig,
  } from "@backflipjs/client";
  import { onMount } from "svelte";

  import { getComponentData } from "../utils/component-data.js";
  import RenderBlock from "./render-block.svelte";

  export let name: string;
  export let input: SuperJSONObject | undefined = undefined;
  export let defaultConfig: RenderedComponentConfig | undefined = undefined;
  let promise: Promise<RenderedComponentConfig | Error | null>;

  onMount(() => {
    if (typeof window !== "undefined") {
      promise = getComponentData(name, input);
    }
  });
</script>

{#await promise}
  <slot name="loading" />
{:then result}
  {#if result instanceof Error}
    <slot name="error" />
  {:else if result === null}
    {#if defaultConfig}
      <RenderBlock config={defaultConfig} />
    {:else}
      <slot name="fallback" />
    {/if}
    <slot name="fallback" />
  {:else}
    <RenderBlock config={result} />
  {/if}
{:catch}
  <slot name="error" />
{/await}

// packages/react/src/components/render-component.tsx
import {
  type RenderedComponentConfig,
  type SuperJSONObject,
} from "@backflipjs/client";

import { useComponentData } from "../hooks/use-component-data";
import { RenderBlock } from "./render-block";

export interface RenderContentProps {
  name: string;
  default?: RenderedComponentConfig;
  error?: React.ReactNode | React.ReactNode[];
  fallback?: React.ReactNode | React.ReactNode[];
  input?: SuperJSONObject;
  loading?: React.ReactNode | React.ReactNode[];
}

export function RenderComponent({
  name,
  default: defaultData,
  error: renderError,
  input,
  fallback: renderFallback,
  loading: renderLoading,
}: RenderContentProps) {
  const { data: contentData, loading, error } = useComponentData(name, input);

  if (loading) {
    if (renderLoading) {
      return <>{renderLoading}</>;
    }

    return null;
  }

  if (error && renderError) {
    return <>{renderError}</>;
  }

  if (!contentData && !loading) {
    if (defaultData) {
      return <RenderBlock {...defaultData} />;
    }

    if (renderFallback) {
      return <>{renderFallback}</>;
    }

    return null;
  }

  // biome-ignore lint/style/noNonNullAssertion: we know contentData is defined
  return <RenderBlock {...contentData!} />;
}
